# Generated by Django 6.0.7 on 2026-08-01 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clp',
            fields=[
                ('idclp', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
                ('ip', models.GenericIPAddressField()),
                ('porta', models.CharField(max_length=45)),
                ('ativo', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'clp',
            },
        ),
    ]
